#!/bin/bash

#pybot - A command line tool to start pybot.py via the command line
#For LINUX Distributions

{
    FULL_PATH=$(find /home -name "client")
    cd $FULL_PATH
    python3 client.py
} || { # catch
    echo Fatal Error:
    set -e
}
